### ISSUE TITLE
List of all students

### ISSUE THREAD

**Issue by Kheirah** [Kheirah/capstone-project#1]
## Value Proposition

**As a** student
**I want to** be able to select a student
**so that** I can guess whose picture is displayed
​
## Description
![US1](https://github.com/Kheirah/capstone-project/assets/22839911/de5070b3-c1ad-4d0b-91be-fb0d431dcbad)

## Acceptance Criteria

- [ ] All students are displayed as a list
- [ ] Only one student at a time can be selected
- [ ] An image is displayed
      ​

## Tasks

- [ ] create a new branch
- [ ] install localstoragestate
- [ ] add state for the list
- [ ] list all students such that they are visible, add a scrollbar if necessary
- [ ] add state for the currently selected student
- [ ] add styling for the selected element
- [ ] add an array of images
- [ ] randomly select one image to display on the page
​

## Complexity

XL
